# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kunal/Desktop/final-project-chong039-kmitt006-zwen012

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kunal/Desktop/final-project-chong039-kmitt006-zwen012

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kunal/Desktop/final-project-chong039-kmitt006-zwen012/CMakeFiles /Users/kunal/Desktop/final-project-chong039-kmitt006-zwen012//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kunal/Desktop/final-project-chong039-kmitt006-zwen012/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named print_test

# Build rule for target.
print_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_test
.PHONY : print_test

# fast build rule for target.
print_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/build
.PHONY : print_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

AppointmentFactory.o: AppointmentFactory.cpp.o

.PHONY : AppointmentFactory.o

# target to build an object file
AppointmentFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/AppointmentFactory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AppointmentFactory.cpp.o
.PHONY : AppointmentFactory.cpp.o

AppointmentFactory.i: AppointmentFactory.cpp.i

.PHONY : AppointmentFactory.i

# target to preprocess a source file
AppointmentFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/AppointmentFactory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AppointmentFactory.cpp.i
.PHONY : AppointmentFactory.cpp.i

AppointmentFactory.s: AppointmentFactory.cpp.s

.PHONY : AppointmentFactory.s

# target to generate assembly for a file
AppointmentFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/AppointmentFactory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AppointmentFactory.cpp.s
.PHONY : AppointmentFactory.cpp.s

Calendar.o: Calendar.cpp.o

.PHONY : Calendar.o

# target to build an object file
Calendar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Calendar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Calendar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Calendar.cpp.o
.PHONY : Calendar.cpp.o

Calendar.i: Calendar.cpp.i

.PHONY : Calendar.i

# target to preprocess a source file
Calendar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Calendar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Calendar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Calendar.cpp.i
.PHONY : Calendar.cpp.i

Calendar.s: Calendar.cpp.s

.PHONY : Calendar.s

# target to generate assembly for a file
Calendar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Calendar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Calendar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Calendar.cpp.s
.PHONY : Calendar.cpp.s

CalendarInterface.o: CalendarInterface.cpp.o

.PHONY : CalendarInterface.o

# target to build an object file
CalendarInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalendarInterface.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/CalendarInterface.cpp.o
.PHONY : CalendarInterface.cpp.o

CalendarInterface.i: CalendarInterface.cpp.i

.PHONY : CalendarInterface.i

# target to preprocess a source file
CalendarInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalendarInterface.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/CalendarInterface.cpp.i
.PHONY : CalendarInterface.cpp.i

CalendarInterface.s: CalendarInterface.cpp.s

.PHONY : CalendarInterface.s

# target to generate assembly for a file
CalendarInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalendarInterface.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/CalendarInterface.cpp.s
.PHONY : CalendarInterface.cpp.s

ClassFactory.o: ClassFactory.cpp.o

.PHONY : ClassFactory.o

# target to build an object file
ClassFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ClassFactory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ClassFactory.cpp.o
.PHONY : ClassFactory.cpp.o

ClassFactory.i: ClassFactory.cpp.i

.PHONY : ClassFactory.i

# target to preprocess a source file
ClassFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ClassFactory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ClassFactory.cpp.i
.PHONY : ClassFactory.cpp.i

ClassFactory.s: ClassFactory.cpp.s

.PHONY : ClassFactory.s

# target to generate assembly for a file
ClassFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ClassFactory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ClassFactory.cpp.s
.PHONY : ClassFactory.cpp.s

DayIndex.o: DayIndex.cpp.o

.PHONY : DayIndex.o

# target to build an object file
DayIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayIndex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DayIndex.cpp.o
.PHONY : DayIndex.cpp.o

DayIndex.i: DayIndex.cpp.i

.PHONY : DayIndex.i

# target to preprocess a source file
DayIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayIndex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DayIndex.cpp.i
.PHONY : DayIndex.cpp.i

DayIndex.s: DayIndex.cpp.s

.PHONY : DayIndex.s

# target to generate assembly for a file
DayIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayIndex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DayIndex.cpp.s
.PHONY : DayIndex.cpp.s

DayState.o: DayState.cpp.o

.PHONY : DayState.o

# target to build an object file
DayState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayState.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/DayState.cpp.o
.PHONY : DayState.cpp.o

DayState.i: DayState.cpp.i

.PHONY : DayState.i

# target to preprocess a source file
DayState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayState.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/DayState.cpp.i
.PHONY : DayState.cpp.i

DayState.s: DayState.cpp.s

.PHONY : DayState.s

# target to generate assembly for a file
DayState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DayState.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/DayState.cpp.s
.PHONY : DayState.cpp.s

Event.o: Event.cpp.o

.PHONY : Event.o

# target to build an object file
Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Event.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Event.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Event.cpp.o
.PHONY : Event.cpp.o

Event.i: Event.cpp.i

.PHONY : Event.i

# target to preprocess a source file
Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Event.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Event.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Event.cpp.i
.PHONY : Event.cpp.i

Event.s: Event.cpp.s

.PHONY : Event.s

# target to generate assembly for a file
Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Event.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Event.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/Event.cpp.s
.PHONY : Event.cpp.s

EventFactory.o: EventFactory.cpp.o

.PHONY : EventFactory.o

# target to build an object file
EventFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EventFactory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/EventFactory.cpp.o
.PHONY : EventFactory.cpp.o

EventFactory.i: EventFactory.cpp.i

.PHONY : EventFactory.i

# target to preprocess a source file
EventFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EventFactory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/EventFactory.cpp.i
.PHONY : EventFactory.cpp.i

EventFactory.s: EventFactory.cpp.s

.PHONY : EventFactory.s

# target to generate assembly for a file
EventFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EventFactory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/EventFactory.cpp.s
.PHONY : EventFactory.cpp.s

Minute.o: Minute.cpp.o

.PHONY : Minute.o

# target to build an object file
Minute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Minute.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Minute.cpp.o
.PHONY : Minute.cpp.o

Minute.i: Minute.cpp.i

.PHONY : Minute.i

# target to preprocess a source file
Minute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Minute.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Minute.cpp.i
.PHONY : Minute.cpp.i

Minute.s: Minute.cpp.s

.PHONY : Minute.s

# target to generate assembly for a file
Minute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Minute.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Minute.cpp.s
.PHONY : Minute.cpp.s

MonthIndex.o: MonthIndex.cpp.o

.PHONY : MonthIndex.o

# target to build an object file
MonthIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthIndex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MonthIndex.cpp.o
.PHONY : MonthIndex.cpp.o

MonthIndex.i: MonthIndex.cpp.i

.PHONY : MonthIndex.i

# target to preprocess a source file
MonthIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthIndex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MonthIndex.cpp.i
.PHONY : MonthIndex.cpp.i

MonthIndex.s: MonthIndex.cpp.s

.PHONY : MonthIndex.s

# target to generate assembly for a file
MonthIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthIndex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MonthIndex.cpp.s
.PHONY : MonthIndex.cpp.s

MonthState.o: MonthState.cpp.o

.PHONY : MonthState.o

# target to build an object file
MonthState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthState.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/MonthState.cpp.o
.PHONY : MonthState.cpp.o

MonthState.i: MonthState.cpp.i

.PHONY : MonthState.i

# target to preprocess a source file
MonthState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthState.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/MonthState.cpp.i
.PHONY : MonthState.cpp.i

MonthState.s: MonthState.cpp.s

.PHONY : MonthState.s

# target to generate assembly for a file
MonthState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MonthState.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/MonthState.cpp.s
.PHONY : MonthState.cpp.s

WeekIndex.o: WeekIndex.cpp.o

.PHONY : WeekIndex.o

# target to build an object file
WeekIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekIndex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/WeekIndex.cpp.o
.PHONY : WeekIndex.cpp.o

WeekIndex.i: WeekIndex.cpp.i

.PHONY : WeekIndex.i

# target to preprocess a source file
WeekIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekIndex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/WeekIndex.cpp.i
.PHONY : WeekIndex.cpp.i

WeekIndex.s: WeekIndex.cpp.s

.PHONY : WeekIndex.s

# target to generate assembly for a file
WeekIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekIndex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/WeekIndex.cpp.s
.PHONY : WeekIndex.cpp.s

WeekState.o: WeekState.cpp.o

.PHONY : WeekState.o

# target to build an object file
WeekState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekState.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/WeekState.cpp.o
.PHONY : WeekState.cpp.o

WeekState.i: WeekState.cpp.i

.PHONY : WeekState.i

# target to preprocess a source file
WeekState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekState.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/WeekState.cpp.i
.PHONY : WeekState.cpp.i

WeekState.s: WeekState.cpp.s

.PHONY : WeekState.s

# target to generate assembly for a file
WeekState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WeekState.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/WeekState.cpp.s
.PHONY : WeekState.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/client.cpp.s
.PHONY : client.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

testing_main.o: testing_main.cpp.o

.PHONY : testing_main.o

# target to build an object file
testing_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/testing_main.cpp.o
.PHONY : testing_main.cpp.o

testing_main.i: testing_main.cpp.i

.PHONY : testing_main.i

# target to preprocess a source file
testing_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/testing_main.cpp.i
.PHONY : testing_main.cpp.i

testing_main.s: testing_main.cpp.s

.PHONY : testing_main.s

# target to generate assembly for a file
testing_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/print_test.dir/build.make CMakeFiles/print_test.dir/testing_main.cpp.s
.PHONY : testing_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main"
	@echo "... print_test"
	@echo "... test"
	@echo "... AppointmentFactory.o"
	@echo "... AppointmentFactory.i"
	@echo "... AppointmentFactory.s"
	@echo "... Calendar.o"
	@echo "... Calendar.i"
	@echo "... Calendar.s"
	@echo "... CalendarInterface.o"
	@echo "... CalendarInterface.i"
	@echo "... CalendarInterface.s"
	@echo "... ClassFactory.o"
	@echo "... ClassFactory.i"
	@echo "... ClassFactory.s"
	@echo "... DayIndex.o"
	@echo "... DayIndex.i"
	@echo "... DayIndex.s"
	@echo "... DayState.o"
	@echo "... DayState.i"
	@echo "... DayState.s"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... EventFactory.o"
	@echo "... EventFactory.i"
	@echo "... EventFactory.s"
	@echo "... Minute.o"
	@echo "... Minute.i"
	@echo "... Minute.s"
	@echo "... MonthIndex.o"
	@echo "... MonthIndex.i"
	@echo "... MonthIndex.s"
	@echo "... MonthState.o"
	@echo "... MonthState.i"
	@echo "... MonthState.s"
	@echo "... WeekIndex.o"
	@echo "... WeekIndex.i"
	@echo "... WeekIndex.s"
	@echo "... WeekState.o"
	@echo "... WeekState.i"
	@echo "... WeekState.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... testing_main.o"
	@echo "... testing_main.i"
	@echo "... testing_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

